### ISSUE TITLE
Assembly option doesn't produce gfa output

### ISSUE THREAD

**Issue by aysunrhn** [AbeelLab/hat#1]
When you run HAT with the option `-ha True` to assemble haplotypes, the code doesn't produce gfa output. Miniasm comand is missing a pipe.

https://github.com/AbeelLab/hat/blob/08a713bda6d879aa8d381cf8e31095d2a6ee7bcb/hat/HAT_main.py#L191-L193

**Comment by ramin-shirali** [comment]
Thanks for noticing the issue. It is fixed in the latest version (0.1.7).
