### ISSUE TITLE
Clustered short reads files are empty 

### ISSUE THREAD

**Issue by aysunrhn** [AbeelLab/hat#2]
Clustered short read files produced for each haplotype are empty, the `seqtk` command doesn't recognize the "/1" and "/2" additions to the IDs of paired-end reads.

https://github.com/AbeelLab/hat/blob/08a713bda6d879aa8d381cf8e31095d2a6ee7bcb/hat/HAT_main.py#L169-L175

**Comment by ramin-shirali** [comment]
Hi @aysunrhn. I believe this is fixed in the latest version (0.1.8).
